feat: Cancel open listings on nft transfer
decentraland/marketplace pull request #1010
Opened 2022-11-22 17:21 UTC by juanmahidalgo

Closes #1003

2022-11-22 17:44 UTC, LautaroPetaccio requested changes

2022-11-22 17:44 UTC, LautaroPetaccio commented on webapp/src/modules/nft/sagas.spec.ts
> +    it('should dispatch an action signaling the success of the action handling and cancel an existing rental listing', () => {
Would you mind adding a successful test where the NFT doesn't have a rental?

2022-11-23 10:44 UTC, juanmahidalgo commented on webapp/src/modules/nft/sagas.spec.ts
> +    it('should dispatch an action signaling the success of the action handling and cancel an existing rental listing', () => {
for sure, added!

2022-11-23 13:34 UTC, LautaroPetaccio approved these changes

2022-11-23 20:26 UTC, merged