feat: add waitForTx to the accept bid flow
decentraland/marketplace pull request #1100
Opened 2022-12-02 15:47 UTC by juanmahidalgo

Closes #1093

2022-12-02 18:18 UTC, LautaroPetaccio requested changes
Beside these comments, the PR looks great! Thanks for adding the whole set of tests for the sagas, they look great!

2022-12-02 18:18 UTC, LautaroPetaccio commented on webapp/src/modules/bid/actions.ts
> +export const acceptBidtransactionSubmitted = (bid: Bid, txHash: string) =>
Would you mind removing the transaction data from `acceptBidSuccess`?

2022-12-02 18:18 UTC, LautaroPetaccio commented on webapp/src/modules/analytics/track.ts
> +  ACCEPT_BID_TRANSACTION_SUBMITTED,
When tracking this action, the payload is built using bid, but `ACCEPT_BID_TRANSACTION_SUBMITTED` is not receiving a bid when it's created.

2022-12-02 18:18 UTC, LautaroPetaccio commented on webapp/src/modules/bid/actions.ts
> +    ACCEPT_BID_TRANSACTION_SUBMITTED,
We should add bid here to use it later in the track file:
```suggestion
    ACCEPT_BID_TRANSACTION_SUBMITTED,
    bid,
```

2022-12-02 18:18 UTC, LautaroPetaccio commented on webapp/src/modules/bid/sagas.spec.ts
> +      const wallet = { address } as Wallet
This is repeated in some of the tests, if you use a beforeEach on an upper statement, you can re-use them if you want.

2022-12-12 11:09 UTC, juanmahidalgo commented on webapp/src/modules/analytics/track.ts
> +  ACCEPT_BID_TRANSACTION_SUBMITTED,
ooh true, good catch! added!

2022-12-12 11:09 UTC, juanmahidalgo commented on webapp/src/modules/bid/sagas.spec.ts
> +      const wallet = { address } as Wallet
for sure, updated!

2022-12-12 11:09 UTC, juanmahidalgo commented on webapp/src/modules/bid/actions.ts
> +export const acceptBidtransactionSubmitted = (bid: Bid, txHash: string) =>
sure, updated!

2022-12-12 12:25 UTC, LautaroPetaccio approved these changes

2022-12-12 12:37 UTC, merged