fix: Don't make get contracts request on startup
decentraland/marketplace pull request #1162
Opened 2022-12-22 20:26 UTC by fzavalia

2022-12-22 20:44 UTC, fzavalia commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  useEffect(() => {
Fetches the name of the contract to replace the stub matic collection name if that is the case

2022-12-22 20:44 UTC, fzavalia commented on webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.tsx
> +      {isFetchingAuthorizations ? (
Added a little spinner to the rentals modal for when authorizations are being fetched.

2022-12-22 20:46 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +  useEffect(() => {
Will fetch contracts when entering the page and when the address changes. 
It is possible to store if they were already fetched for the user once so thay are not fetched everytime the user enters the page in the same session.

2022-12-22 20:47 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +                        <div className="authorization-checks">
Added the mana atuhorization for rentals that was missing

2022-12-22 20:47 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +                          <Authorization
Added the bids authorization for matic that was missing

2022-12-22 20:50 UTC, fzavalia commented on webapp/src/modules/contract/sagas.spec.ts
> +    // TODO: handleFetchContractsSuccess is breaking the test, fix it.
I skipped the tests that were broken with this changes in order to be able to progress. Will fix and add more tests next

2022-12-22 20:51 UTC, fzavalia commented on webapp/src/modules/contract/sagas.ts
> +export function* handleFetchContractsSuccess() {
Will fetch all authorizations when contracts are fetched form the server. This was moved from the wallet saga.

2022-12-22 20:51 UTC, fzavalia commented on webapp/src/modules/contract/sagas.ts
> +  const stateAuthorizations: Authorization[] = yield select(getAuthorizations)
In order to prevent duplication of authorizations, I'm removing authorizations that are already stored and just requesting the new ones.

2022-12-22 20:54 UTC, fzavalia commented on webapp/src/modules/contract/selectors.ts
> +    return found || null
Throwing an error here was messing things up so I removed it

2022-12-22 20:56 UTC, fzavalia commented on webapp/src/modules/contract/utils.ts
> +export function upsertContracts(
This functions takes a list of contracts and upserts another list of contracts into it. 
This is because now, contracts are fetched on various occasions and we don't want duplications nor missing previously defined contracts.

2022-12-22 21:00 UTC, fzavalia commented on webapp/src/modules/nft/sagas.ts
> +      yield put(upsertContracts(newContracts))
Static contracts are defined in the store from the beginning, meaning that nfts that have different addresses are warables or emotes.
For these contracts that do not exist in the store at the moment, I generate a stub contract for them to be available.

2022-12-22 21:01 UTC, fzavalia commented on webapp/src/modules/nft/sagas.ts
> +    if (!contract) {
Same as before, I generate the stub for the dynamic contract that is not present in the store.

2022-12-22 21:01 UTC, fzavalia commented on webapp/src/modules/vendor/decentraland/ContractService.ts
> -export enum ContractName {
Moved this and contracts to the contracts.ts file

2022-12-22 21:02 UTC, fzavalia commented on webapp/src/modules/wallet/sagas.ts
> -  yield takeEvery(CONNECT_WALLET_SUCCESS, handleWallet)
I don't need any of this anymore because authorisations are fetched differently now.

2022-12-26 13:50 UTC, fzavalia commented on webapp/src/modules/contract/sagas.spec.ts
> +    // TODO: handleFetchContractsSuccess is breaking the test, fix it.
Unskipped the tests 👍

2022-12-26 17:26 UTC, LautaroPetaccio requested changes

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  const hasFetchedContractName = useRef(false)
I think we need a loader that shows the user that the authorization or the contract name is being fetched, right?

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  const hasFetchedContractName = useRef(false)
Also, what if we initialize `hasFetchedContractName` to false if the contract does not have a name or has the default name set? That could avoid fetching the contract name if the user has already loaded it.

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +  useEffect(() => {
If you want, you can create a ticket to make this improvement.

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +                          <Authorization
Great catch!

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/modules/contract/utils.spec.ts
> +  it('should return a string with the contract address and chain id', () => {
```suggestion
  it('should return a string that contains the address, the authorized address, the contract address and the chain Id', () => {
```

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/modules/contract/utils.spec.ts
> +})
As it's only one case, you can remove the describe that is used for the context if you want and just have the address be lowercased:
```suggestion
describe('when calling getStubMaticCollectionContract', () => {
    it('should return stub matic collection contract with the address lowercased', () => {
      expect(getStubMaticCollectionContract('ADDRESS')).toEqual({
        address: 'address',
        category: NFTCategory.WEARABLE,
        chainId: undefined,
        name: STUB_MATIC_COLLECTION_CONTRACT_NAME,
        network: Network.MATIC,
        vendor: VendorName.DECENTRALAND
      })
    })
})
```
Also, why is the `chainId` undefined?

2022-12-26 17:26 UTC, LautaroPetaccio commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  useEffect(() => {
What do you think about adding this Github comment as a code comment?

2022-12-26 17:39 UTC, fzavalia commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  useEffect(() => {
👍

2022-12-26 17:44 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.tsx
> +  useEffect(() => {
https://github.com/decentraland/marketplace/issues/1167

2022-12-26 17:48 UTC, fzavalia commented on webapp/src/modules/contract/sagas.ts
> +  const stateAuthorizations: Authorization[] = yield select(getAuthorizations)
👍

2022-12-26 17:49 UTC, fzavalia commented on webapp/src/modules/contract/utils.ts
> +export function upsertContracts(
But isn't merging some sort of upsert? It inserts contract that are not present, and updates contracts that are present.

2022-12-26 17:54 UTC, fzavalia commented on webapp/src/modules/nft/sagas.ts
> +    if (!contract) {
👍

2022-12-26 18:01 UTC, fzavalia commented on webapp/src/components/AuthorizationModal/AuthorizationModal.container.ts
> +import { upsertContracts } from '../../modules/contract/actions'
👍

2022-12-26 18:01 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.container.ts
> +} from '../../modules/contract/actions'
👍

2022-12-26 18:02 UTC, fzavalia commented on webapp/src/modules/nft/sagas.ts
> +import { Contract } from '../vendor/services'
👍

2022-12-26 18:03 UTC, fzavalia commented on webapp/src/modules/nft/sagas.spec.ts
> +import { getStubMaticCollectionContract } from '../contract/utils'
👍

2022-12-26 18:23 UTC, fzavalia commented on webapp/src/modules/contract/sagas.spec.ts
> +        ])
The authorizations request is done in a different sagas that handles the fetchContractsSuccess. Still I'll add a test for what you are saying.

2022-12-26 19:08 UTC, fzavalia commented on webapp/src/modules/contract/sagas.spec.ts
> +        ])
Done 👍

2022-12-26 19:18 UTC, fzavalia commented on webapp/src/modules/contract/reducer.ts
> +    }
👍

2022-12-26 19:19 UTC, fzavalia commented on webapp/src/components/SettingsPage/SettingsPage.container.ts
> +      isLoadingType(getContractLoading(state), FETCH_CONTRACTS_REQUEST),
The authorizations loader is there (the one for FETCH_AUTHORIZATIONS_REQUEST)

2022-12-26 19:20 UTC, fzavalia commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +import ERC721ABI from '../../contracts/ERC721.json'
👍

2022-12-26 19:26 UTC, fzavalia commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  const hasFetchedContractName = useRef(false)
https://github.com/decentraland/marketplace/issues/1169 created the issue for the loader. 

For the second thing, the name will only be fetched if the contract has the name of a stub collection, so there will no unnecessary fetches.

2022-12-26 19:37 UTC, LautaroPetaccio commented on webapp/src/components/SettingsPage/SettingsPage.container.ts
> +      isLoadingType(getContractLoading(state), FETCH_CONTRACTS_REQUEST),
My bad 🤦

2022-12-26 19:51 UTC, LautaroPetaccio approved these changes

2022-12-26 21:03 UTC, merged