Feat: list for sale modal
decentraland/marketplace pull request #1320
Opened 2023-01-18 15:43 UTC by flobarreto

<img width="974" alt="image" src="https://user-images.githubusercontent.com/32873485/213217298-7a8e0a44-be7f-4f7e-86e9-f945053651de.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/32873485/213217376-b3903152-6435-4b63-9eee-ac72358f035f.png">

2023-01-18 16:43 UTC, LautaroPetaccio requested changes
Looks good 👍 , it just needs a couple of changes.

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/ManageAssetPage/Sell/Sell.container.ts
> +  }
This doesn't seem to be in used, would you mind removing it?

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/ManageAssetPage/Sell/Sell.tsx
> +    order = null,
Would you mind explaining why is this variable set as null here?

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Would you mind removing this rule?

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +  const [stepper, setStepper] = useState(StepperValues.SELL_MODAL)
If I'm not wrong, this defines the `step` of the `stepper`, what do you think about calling it step?
```suggestion
  const [step, setStep] = useState(StepperValues.SELL_MODAL)
```

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.css
> +.fields-container {
Would you mind changing the styles file to use CSS modules? We're using modules for the new components.
Remember that you will need to use `:global` for the global classes.

2023-01-18 16:43 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.css
> +  width: 26px !important;
Is it possible to remove the importants by being more specific on the class definitions?

2023-01-18 21:00 UTC, flobarreto commented on webapp/src/components/ManageAssetPage/Sell/Sell.tsx
> +    order = null,
not needed

2023-01-20 13:25 UTC, LautaroPetaccio requested changes

2023-01-20 13:25 UTC, LautaroPetaccio commented on webapp/src/components/AuthorizationModal/AuthorizationModal.tsx
> +  // const hasFetchedAuthorizations = useRef(false)
Would you mind removing this comment?

2023-01-23 12:28 UTC, LautaroPetaccio approved these changes

2023-01-23 12:33 UTC, merged