feat: mobile links to builder not available
decentraland/marketplace pull request #1332
Opened 2023-01-23 13:25 UTC by flobarreto

closes #1316

2023-01-23 20:45 UTC, fzavalia commented
![image](https://user-images.githubusercontent.com/24811313/214145997-a2cf3b88-e29e-4ed7-8b43-c17a9d985e21.png)

The icon </> looks bigger than the rest on mobile, and the text is not aligned, maybe we should do something to align everything

2023-01-24 12:43 UTC, flobarreto commented
![image](https://user-images.githubusercontent.com/32873485/214294531-21175309-9b34-4c9f-be94-7576b8d8433a.png)

what about now?

2023-01-24 13:40 UTC, fzavalia requested changes

2023-01-24 13:40 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/RentConfirmedModal.tsx
> +            {CTAs.map((cta, i) =>
I'm not a fan of doing a map of the ctas when they are not dynamic. Can we write them directly into the jsx and disable the corresponding one if the viewport is mobile?

2023-01-24 14:27 UTC, LautaroPetaccio commented on webapp/src/components/Modals/RentConfirmedModal/RentConfirmedModal.tsx
> +            {CTAs.map((cta, i) =>
Be aware that there are only a few things that change in the code and they can be highly abstracted. We can create sub-components to keep the code abstraction though.

2023-01-24 18:47 UTC, fzavalia requested changes

2023-01-24 18:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/CTA.tsx
> +const CTA = ({ cta }: Props) => {
I think it would be cleaner that this component received as props: to, icon and disabled. Receiving an object with its props seems unnecessary and the index is kind of abstract for this component.

if disabled is true, do the same as you are doing here as if it were  isMobileView.

2023-01-24 18:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/CTA.tsx
> +import styles from './RentConfirmedModal.module.css'
Styles used here should belong to a CTA.module.css file

2023-01-24 18:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/CTA.tsx
> +import { CTAProps } from './RentConfirmedModal.types'
Types used here should belong to a CTA.types.ts file

2023-01-24 18:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/RentConfirmedModal.tsx
> +const CTAs: CTAProps[] = [
This can be remove and placed inside the render like:

```
<CTA to={builderUrl} icon="build-more" disabled={isMobileView} />
<CTA to="https://docs.decentraland.org/creator/development-guide/coding-scenes/" icon="get-creative" />
<CTA to={`${builderUrl}/land`} icon="manage-land" disabled={isMobileView} />
```

2023-01-24 19:47 UTC, fzavalia requested changes

2023-01-24 19:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/CTA/CTA.tsx
> +const CTA = ({ to, name, isDisabledOnMobile }: Props) => {
❤️

2023-01-24 19:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/CTA/CTA.tsx
> +      key={name}
This is not handled in a map so the key is unnecessary

2023-01-24 19:47 UTC, fzavalia commented on webapp/src/components/Modals/RentConfirmedModal/RentConfirmedModal.types.ts
> +export type CTAProps = {
This can be deleted

2023-01-24 19:54 UTC, fzavalia approved these changes
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

2023-01-24 19:55 UTC, merged