style: Use eslint for sorting imports
decentraland/marketplace pull request #1335
Opened 2023-01-23 14:12 UTC by kevinszuchet

Based on [these docs](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)

Closes #1334

2023-01-24 12:47 UTC, cyaiox requested changes

2023-01-24 12:47 UTC, cyaiox commented on webapp/package.json
> +          "newlines-between": "always",
We should use here ```"newlines-between": "never"```

2023-01-24 12:54 UTC, cyaiox commented
Great Job!! this will improve a lot the imports order consistency.

I left a small change request

2023-02-27 20:07 UTC, kevinszuchet commented
Closes by https://github.com/decentraland/eslint-config-dapps

2023-02-27 20:07 UTC, closed without merging