feat: edit and delete listing for sale
decentraland/marketplace pull request #1339
Opened 2023-01-23 20:57 UTC by flobarreto

2023-01-24 12:47 UTC, LautaroPetaccio requested changes

2023-01-24 12:47 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.container.ts
> +    isLoadingCancel: isLoadingType(getLoading(state), CANCEL_ORDER_REQUEST)
What do you think about renaming this to:
```suggestion
    isCancelling: isLoadingType(getLoading(state), CANCEL_ORDER_REQUEST)
```
it follows the same format as `isAuthorizing`.

2023-01-24 12:47 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +        <div className={styles.fieldsContainer}>
The confirmation of the cancelling of a listing is different than the one of the creation, I would create another step, called `CONFIRM_CANCEL` with the content and the buttons to confirm the removal of the listing.
<img width="450" alt="Screenshot 2023-01-24 at 13 38 31" src="https://user-images.githubusercontent.com/1120791/214293688-505551b5-2f79-4842-b849-0403b88e98d3.png">

2023-01-24 12:47 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            {isUpdate ? t('cancel_sale_page.title') : t('global.cancel')}
When on `edit mode`, this button should say `Remove listing` instead of `Cancel` as that's the way it's designed in the figma.

2023-01-24 12:47 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +  const isDisabledConfirm = isCancel
What do you think about renaming this variable as such:
```suggestion
  const isConfirmDisabled = isCancel
```
This is because in english, the noun goes before the adjective so it makes the variable easier to read.

2023-01-24 12:47 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +      setIsCancel(true)
This can be removed if we create the new step.

2023-01-24 19:37 UTC, flobarreto commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            {isUpdate ? t('cancel_sale_page.title') : t('global.cancel')}
it says that :) 
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/32873485/214391467-36eafe6d-f1e0-4215-bb84-dd7778192055.png">

2023-01-25 09:52 UTC, LautaroPetaccio requested changes
Some small changes but looks great 👍

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            disabled={isCreatingOrder || isCancelling}
```suggestion
            disabled={isCreatingOrder}
```

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            disabled={isCreatingOrder || isCancelling}
```suggestion
            disabled={isCreatingOrder}
```

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            loading={isCreatingOrder || isCancelling}
```suggestion
            loading={isCreatingOrder}
```

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            }}
```suggestion
            onClick={onClose}
```

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            isAuthorizing || isCreatingOrder || isCancelling
```suggestion
            isAuthorizing || isCreatingOrder
```

2023-01-25 09:52 UTC, LautaroPetaccio commented on webapp/src/components/Modals/SellModal/SellModal.tsx
> +            isCreatingOrder || isCancelling
```suggestion
            isCreatingOrder
```

2023-01-25 11:47 UTC, LautaroPetaccio approved these changes
Merge it! 🚀

2023-01-25 11:49 UTC, merged