feat: Core flow after purchasing NFTs with card
decentraland/marketplace pull request #1344
Opened 2023-01-24 16:19 UTC by kevinszuchet

Closes #1262 
Closes #1270

2023-01-25 15:37 UTC, fzavalia requested changes

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/components/BuyPage/StatusPage/index.ts
> +import StatusPage from './StatusPage.containter'
Typo `containter`

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/components/Routes/Routes.tsx
> +        <Route
This routes shouldn't be declared if the feature flag is disabled

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/modules/asset/sagas.ts
> +    const shouldRedirect = [
Isn't it easier to `window.location.pathname === statusPagePathname`?

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/modules/item/sagas.spec.ts
> +import {
Move import on top of ./sagas

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/modules/item/sagas.ts
> +    // TODO (buy nfts with card): do we need the txHash here?
🤷

2023-01-25 15:37 UTC, fzavalia commented on webapp/src/modules/order/reducer.spec.ts
> +failureActions.forEach(action => {
Is this way of testing taken from somewhere else?

2023-01-25 17:05 UTC, kevinszuchet commented on webapp/src/components/BuyPage/StatusPage/StatusPage.css
> +  z-index: 100;
The default `z-index` of the UI package loader is 1000. With that value, the spinner overlaps the Transak widget.

2023-01-25 17:48 UTC, kevinszuchet commented on webapp/src/components/BuyPage/StatusPage/StatusPage.tsx
> +      history.replace(locations.root())
Which option do you think is more suitable between dispatching the replace action manually or using the Redirect component?

2023-01-25 17:57 UTC, kevinszuchet commented on webapp/src/modules/asset/sagas.ts
> +    const shouldRedirect = [
If it hasn't been redirected to the processing status page, this will always be false. We should also redirect if the user  still see the Buy NFTs with Card page.

2023-01-25 18:03 UTC, kevinszuchet commented on webapp/src/modules/order/reducer.spec.ts
> +failureActions.forEach(action => {
Yes, it is. May I abstract the logic and reuse it in the following reducers test files: event, item, and order?

2023-01-25 19:27 UTC, fzavalia commented on webapp/src/components/BuyPage/StatusPage/StatusPage.tsx
> +      history.replace(locations.root())
You can use the Redirect component as well, it is provided by the connected react router so it should work. Just check the emitted actions to see that

2023-01-25 19:28 UTC, fzavalia commented on webapp/src/modules/order/reducer.spec.ts
> +failureActions.forEach(action => {
good :)

2023-01-26 12:45 UTC, fzavalia submitted a review, later dismissed

2023-01-26 15:17 UTC, fzavalia approved these changes

2023-01-26 15:21 UTC, merged