Feat/list for rent again
decentraland/marketplace pull request #1347
Opened 2023-01-25 01:10 UTC by flobarreto

closes #778 

<img width="716" alt="image" src="https://user-images.githubusercontent.com/32873485/214457389-bc1e75fd-a5c3-4562-8890-1425d5a90dae.png">

2023-01-27 08:11 UTC, LautaroPetaccio requested changes
Looks great, just some minor comments 👍

2023-01-30 12:16 UTC, LautaroPetaccio approved these changes

2023-01-30 16:17 UTC, LautaroPetaccio submitted a review, later dismissed

2023-02-02 14:02 UTC, kevinszuchet commented on webapp/src/components/Modals/RentalListingModal/InformationStep/InformationStep.container.ts
> +export default connect(mapState, null)(InformationStep)
Is this container needed? There is no mapping. We may remove it and point the index to the component itself. WDYT?

2023-02-02 14:09 UTC, kevinszuchet approved these changes

2023-02-02 15:37 UTC, cyaiox commented on webapp/src/components/ManageAssetPage/Rent/Rent.tsx
> +                              address={rental!.tenant!}
could you please validate `rental` and `rental.tenant` exists with `rentalEnded` to avoid the `non-null assertion` operator?

2023-02-02 20:53 UTC, kevinszuchet approved these changes

2023-02-08 14:01 UTC, merged