Feat: owners table
decentraland/marketplace pull request #1459
Opened 2023-03-09 20:54 UTC by flobarreto

closes #1438

2023-03-10 17:47 UTC, fzavalia requested changes

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +import styles from './ItemDetail.module.css'
Move this import to the bottom of the import list

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +import { Dropdown, Tabs } from 'decentraland-ui'
Move this import underneath @dcl/schemas

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +import { OrderDirection } from '../OwnersTable/OwnersTable.types'
Move this import on top of 
```
import { TransactionHistory } from '../TransactionHistory'
```

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +  const [owners, setOwners] = useState([] as Array<OwnersResponse>)
```suggestion
  const [owners, setOwners] = useState<OwnersResponse[]>([])
```

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +      nftAPI
Are there other uses in the app fetching for data without going through sagas and redux?

2023-03-10 17:47 UTC, fzavalia commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.types.ts
> +}
Add a extra line

2023-03-10 18:45 UTC, flobarreto commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +      nftAPI
yes, the ones using pagination such as Transaction history

2023-03-10 18:47 UTC, fzavalia requested changes

2023-03-10 18:47 UTC, fzavalia commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +import styles from './ItemDetail.module.css'
Styles should always go as the last import in the list

2023-03-10 19:21 UTC, fzavalia commented
https://user-images.githubusercontent.com/24811313/224406870-d7a85418-199b-4fe5-897f-4458f246e02e.mov

Wouldn't it be nice to show a loading when the owners are being fetched from the server?

Also would be nice to show a message when no owners of an item are found (Because it is a new item for example and none were minted)

2023-03-13 11:40 UTC, juanmahidalgo reviewed
looks good! a few comments/suggestions for improvements

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/package.json
> +}
can we add the end of file back? :)

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css
> +.tableContainer{
```suggestion
.tableContainer {
```
can we run prettier in this file please?

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +        <div className={styles.tableContainer}>
I would wrap this whole table in a different component, as it was with the `TransactionHistory` and it is in the `actions` prop with the `SaleActionBox`. It could be a `ListingsTable` (and it would have the owners as well).

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
> +            <TransactionHistory asset={item} />
```suggestion
            null
```
Can we just render an empty table here? I believe that the `TransactionHistory` is going to be always rendered, underneath this new table.

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +  const [page, setPage] = useState(1)
```suggestion
  const [page, setPage] = useState(INITIAL_PAGE)
```
can we store the 1 in a variable? just to avoid having [magic numbers](https://eslint.org/docs/latest/rules/no-magic-numbers)

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +  const [totalPages, setTotalPages] = useState(1)
```suggestion
  const [totalPages, setTotalPages] = useState()
```
I believe this should start as `undefined` or `null` until we know how many pages there are, wdyt?

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +        orderDirection: orderDirection
```suggestion
        orderDirection
```

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +        contractAddress: asset.contractAddress!,
```suggestion
        contractAddress: asset.contractAddress,
```
I believe the `!` is not needed here

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +    if (asset) {
```suggestion
    if (asset && asset.itemId) {
```
so remove the `!` from line 35 :)

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +                  {t('owners_table.issue_number')}
I believe this translation is missing 
![image](https://user-images.githubusercontent.com/8763687/224689604-a268e4ec-bdd9-425e-9a35-0d41cee31567.png)

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/modules/vendor/decentraland/nft/api.ts
> +import { OwnersFilters, OwnersResponse } from '../../../../components/AssetPage/OwnersTable/OwnersTable.types'
I'm not a fan of a `module` importing types form a component file. I'd rather put them in `webapp/src/modules/vendor/decentraland/nft/types.ts` and then have the react component to import them. WDYT?

2023-03-13 11:40 UTC, juanmahidalgo commented on webapp/src/modules/vendor/decentraland/nft/api.ts
> +  async getOwners( params: OwnersFilters): Promise<{data: OwnersResponse[], total: number}> {
```suggestion
  async getOwners( params: OwnersFilters): Promise<{ data: OwnersResponse[], total: number }> {
```
can we run prettier in this file please :) ?

2023-03-13 11:43 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx
> +        <Loader />
```suggestion
        <Loader active />
```
`active` prop is missing, otherwise it won't be shown

2023-03-14 18:37 UTC, fzavalia approved these changes

2023-03-14 19:16 UTC, merged