feat: Add pick unpick favorite mechanism
decentraland/marketplace pull request #1505
Opened 2023-03-29 09:45 UTC by kevinszuchet

Closes #1484

2023-03-29 16:03 UTC, LautaroPetaccio requested changes
Looks great, it adds the functionality we wanted for Favorites! I've left some comments to review.

2023-03-29 16:03 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/reducer.spec.ts
> +  describe(`when reducing the "${action.failure.type}" action`, () => {
If you want, you can use `describe.each`, there are some examples where Meli used it, it might be simpler.

2023-03-29 16:22 UTC, kevinszuchet commented on webapp/src/components/FavoritesCounter/FavoritesCounter.spec.tsx
> +  describe('when the item is not favorite by the user', () => {
Spell checking auto fix. I'll revert it.

2023-03-29 17:22 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/sagas.ts
> +      yield put(openModal('LoginModal'))
We must take into consideration that the `LoginModal` can be closed, so we need to track that action to cancel this one.

2023-03-29 17:29 UTC, kevinszuchet commented on webapp/src/components/FavoritesCounter/FavoritesCounter.tsx
> +      onClick={onClick}
Yes, you're right!

2023-03-29 18:08 UTC, LautaroPetaccio commented on webapp/src/modules/toast/sagas.ts
> +  yield put(showToast(getPickItemAsFavoriteFailureToast(item), 'bottom center'))
Re-reading the code, the best thing to do is to use the channel.

2023-03-30 13:19 UTC, LautaroPetaccio requested changes

2023-03-30 13:19 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/selectors.spec.ts
> +describe('when getting the if an item is picked by user', () => {
Would you mind adding a test to exercise the case where the favorite for the item doesn't exist?
The same goes for the `getCount` selector.

2023-03-30 13:19 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/sagas.ts
> +      if (close) return
If we're handling the `PICK_ITEM_AS_FAVORITE_REQUEST` action, we've already affected the redux state, meaning that the state has a loading action into it. You can create a new action, called `cancelPickItemAsFavorite` that removes the loading from the state and is dispatched in this case.

2023-03-30 13:19 UTC, LautaroPetaccio commented on webapp/src/components/FavoritesCounter/FavoritesCounter.container.ts
> +      : false,
If the user isn't logged in, the pickedByUser property will be false, so there shouldn't be any issues with asking the selector directly for the property.
```suggestion
    isPickedByUser: getIsPickedByUser(state, itemId)
```

2023-03-30 14:06 UTC, LautaroPetaccio approved these changes
Super duper archi mega approved ✅

2023-03-30 14:08 UTC, merged