removed the react-copy-to-clipboard lib
decentraland/marketplace pull request #1506
Opened 2023-03-29 13:02 UTC by Chakravarthy7102

Completely removed the dependency @react-copy-to-clipboard in the project and replaced it with a custom hook to copy the text to clipboard.

2023-03-29 16:59 UTC, LautaroPetaccio requested changes
Hi! Thanks for your contribution to the project. The PR looks great. I've left some comments to address before merging it.

2023-03-29 16:59 UTC, LautaroPetaccio commented on webapp/src/hooks/useCopyToClipboard.tsx
> +}
What if we build this as a un utility function instead of a hook? The main reason is that it doesn't need to store anything or use any other hook to operate.
```suggestion
const copyToClipboard = (onCopy: () => void) => {
    navigator.clipboard.writeText(text)
    onCopy()
}
```

2023-03-30 05:14 UTC, Chakravarthy7102 commented on webapp/src/hooks/useCopyToClipboard.tsx
> +}
Yup!, your argument make sense a lot, there is no need for a hook for this. I'll change it and also do the other changes you suggested.

2023-03-30 05:21 UTC, Chakravarthy7102 commented on webapp/src/hooks/useCopyToClipboard.tsx
> +}
But here in this copyToClipboard function, we also need to add the text as parameter to access the text inside the func
`const copyToClipboard = (text:string, onCopy:()=>void)`, if there is possibility please edit your suggestion or else I'll make a new pull request!

2023-03-31 11:24 UTC, LautaroPetaccio requested changes
Just one more little thing and we're ready to go.

2023-03-31 11:24 UTC, LautaroPetaccio commented on webapp/src/lib/copyText.ts
> +const copyText = (text: string, onCopy: () => void) => {
Would you mind adding a test for this function?
I've [here](https://www.notion.so/decentraland/Testing-standards-46797744fccf4f3eba52335f9866d0eb) the testing standards we're using for you to take a look.
It would be nice to have a test that assert that when calling this function, the clipboard gets written and that `onCopy` gets called.
It should look something like:
```
describe('when calling the copy text function', () => {
  let writeTextSpy: jest.SpyInstance
  let onCopyMock: jest.Mock
  beforeEach(() => {
    onCopyMock = jest.fn()
    writeTextSpy = jest.spyOn(navigator.clipboard, 'writeText')
  })

  it('should write the text to the clipboard and execute the onCopy callback', () => {
    copyText('someText', onCopyMock)
    expect(onCopyMock).toHaveBeenCalled()
    expect(writeTextSpy).toHaveBeenCalledWith('someText)
  })
})
```

2023-03-31 14:20 UTC, Chakravarthy7102 commented on webapp/src/lib/copyText.ts
> +const copyText = (text: string, onCopy: () => void) => {
Yup sure will do that!

2023-04-01 12:33 UTC, Chakravarthy7102 commented
tests added! @LautaroPetaccio

2023-04-03 11:51 UTC, LautaroPetaccio approved these changes
Looks great! If you want, you can also replicate this change in the [Builder](https://github.com/decentraland/builder), we'll be glad to have this change there as well.

2023-04-03 11:56 UTC, LautaroPetaccio commented
I'm unable to merge this PR because we require all contributors to sign all commits with their own GPG key as a security measure.

Would you mind:
1. [Creating and adding a GPG key to your Github account](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
2. [Signing all of your commits in this branch](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits)

For the commits to work they must say "Verified" next to them in the Github interface.

2023-04-03 16:39 UTC, Chakravarthy7102 commented
Signed  all the commits, Thanks for linking relevant resources!, I think now we are good to goww!

2023-04-03 16:42 UTC, LautaroPetaccio approved these changes

2023-04-03 16:45 UTC, LautaroPetaccio commented
I'm sorry @Chakravarthy7102, but there are still a few commits that are not signed, all of them must be signed for Github to allow me to merge the PR.
These are the commits in this PR that are not signed:
- 46f81d15904fca99e85bacfc64820a1b669d5040
- c468d34a950c5a05c2cde377da17d8be3c9c03d7
- 451390681ad7ade9e8a845c765b218aa7eecc936
- b9e2569662558ee752247a4dd09fd77f06e2445c
You might need to do a force push after signing them becase the history will change.

2023-04-03 18:44 UTC, Chakravarthy7102 commented
@LautaroPetaccio Hi, I'm not tried different things but couldn't able to verify my all the commits. Instead i guess made lots of bad things into commit history!

One thing that comes into my mind right now to fix this situation is to delete my fork and create a new pull request for this issue.

or any other way that you can suggest would also help!

2023-04-03 18:52 UTC, LautaroPetaccio commented
Hi @Chakravarthy7102, it seems that the history broke. You can delete your branch, close this PR and create a new one with all the commits signed.

2023-04-03 19:03 UTC, closed without merging