feat: Add my lists page
decentraland/marketplace pull request #1519
Opened 2023-04-04 12:11 UTC by kevinszuchet

2023-04-04 21:01 UTC, LautaroPetaccio requested changes
Amazing job! It looks great 🎉

2023-04-04 21:01 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/reducer.ts
> +import { FETCH_ITEMS_SUCCESS, FetchItemsSuccessAction } from '../item/actions'
Would you mind moving this import up?

2023-04-04 21:01 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/reducer.ts
> +    case FETCH_ITEMS_SUCCESS: {
If I'm not wrong, this reducer is missing its test, would you mind adding it?

2023-04-05 15:35 UTC, kevinszuchet commented on webapp/src/modules/transak/sagas.ts
> -    ), */
We've already solved this using JS events. The redirect URL is not needed anymore.

2023-04-05 15:46 UTC, kevinszuchet commented on webapp/src/modules/vendor/decentraland/favorites/api.ts
> +        queryParams.toString()
NSIU. If the parameters are not set in the `queryParams` instance, the called to `toString()` will return an empty string, so the final url will be `${MARKETPLACE_FAVORITES_SERVER_URL}/lists/${listId}/picks?`

2023-04-06 09:25 UTC, kevinszuchet commented on webapp/src/modules/favorites/selectors.ts
> +export const getListId = createSelector<
To be consistent with selectors like: `getContractAddress`, `getTokenId` (they are in the `nft` and `item` selectors files), I'd keep this selector in this file because it's related to the `My Lists` page and the `favorites` module.

2023-04-06 12:54 UTC, LautaroPetaccio requested changes
Looks great, just one last comment.

2023-04-06 12:54 UTC, LautaroPetaccio commented on webapp/src/modules/favorites/reducer.spec.ts
> +  }
Would you mind putting the context building procedures inside a `beforeEach`?
Per standard, we only define variables outside the `beforeEach` if they're `const primitives`, as the can't change.
The same goes for the test down below.

2023-04-06 12:54 UTC, LautaroPetaccio commented on webapp/src/modules/routing/selectors.ts
> +  if (isListsSection(section as Section)) return false
We do! at least for now.

2023-04-06 21:19 UTC, LautaroPetaccio submitted a review, later dismissed
Best PR ever 🚀

2023-04-07 16:53 UTC, LautaroPetaccio approved these changes

2023-04-07 19:21 UTC, merged