feat: Add revoke and grant functionality in authorization modal
decentraland/marketplace pull request #1612
Opened 2023-04-21 21:49 UTC by meelrossi

2023-04-27 21:39 UTC, fzavalia requested changes
The approach is great!

2023-04-27 21:39 UTC, fzavalia commented on webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
> +import withAuthorizedAction from '../../HOC/withAuthorizedAction/withAuthorizedAction'
I'm not a big fan of having an HOC directory because high order components could be any kind of component that handles state or has complex logic. 

Something like `withAuthorizedAction` reminds me more of the decorator pattern.

Not asking to change it, just the reason behind it.

2023-04-27 21:39 UTC, fzavalia commented on webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
> +      onAuthorized: () => onRent(selectedRentalPeriodIndex)
I love this way of providing the action of what to be done after the authorization ❤️

2023-04-27 21:39 UTC, fzavalia commented on webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx
> +import { ContractName } from 'decentraland-transactions'
Beware of import order

2023-04-27 21:39 UTC, fzavalia commented on webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
> +import { ContractName } from 'decentraland-transactions'
Import order

2023-04-27 21:39 UTC, fzavalia commented on webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.container.ts
> +import { Contract } from '../../../../modules/vendor/services'
Import order

2023-04-28 04:25 UTC, meelrossi commented on webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
> +import withAuthorizedAction from '../../HOC/withAuthorizedAction/withAuthorizedAction'
I put it in a hoc folder so that its not dumped on the components folder as everything else, but im ok with moving it, it was just a though to maybe keep it cleaner. As of the name,  it is kind of a decorator as we are adding behavior to the component.

2023-04-28 15:37 UTC, fzavalia commented on webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
> +import withAuthorizedAction from '../../HOC/withAuthorizedAction/withAuthorizedAction'
Let's keep it in mind when adding new components of the kind if we should change it, we can leave it as it is.

2023-04-28 15:53 UTC, fzavalia requested changes
👏

2023-04-28 15:53 UTC, fzavalia commented on webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx
> +    console.log(onAuthorized())
Is this log temporary?

2023-04-28 16:24 UTC, fzavalia approved these changes

2023-04-28 17:27 UTC, merged