feat: add toasts from dapps and handle meta transaction errors
decentraland/marketplace pull request #317
Opened 2021-06-01 16:29 UTC by nicosantangelo

Closes #288

2021-06-01 17:32 UTC, cazala requested changes

2021-06-01 17:32 UTC, cazala commented on webapp/src/modules/toast/toasts.tsx
> +const DISCORD_URL = process.env.REACT_APP_DISCORD_URL
Maybe we should add this to the `.env.example` and the `.ci` folder vars?

2021-06-01 17:32 UTC, cazala commented on webapp/src/modules/toast/sagas.ts
> +  yield takeEvery(CANCEL_ORDER_FAILURE, handleNFTMetaTransactionFailure)
We are missing two meta transaction error actions: `GRANT_TOKEN_FAILURE` and `REVOKE_TOKEN_FAILURE`. Those should use a different handler since they don't have an `nft` property.

2021-06-01 17:32 UTC, cazala commented on webapp/src/modules/toast/sagas.ts
> +  if (nft.network === Network.MATIC) {
Should we also check and ignore errors that include `User denied message signature`? Otherwise we get these toasts when the users rejects the MetaMask prompt.

2021-06-01 17:54 UTC, nicosantangelo commented on webapp/src/modules/toast/sagas.ts
> +  if (nft.network === Network.MATIC) {
Really good point, I think so, I should also check builder for the same thing. I'll try to come up with a way to do that but I think I'll have to compare strings

2021-06-01 17:54 UTC, nicosantangelo commented on webapp/src/modules/toast/toasts.tsx
> +const DISCORD_URL = process.env.REACT_APP_DISCORD_URL
Sorry, yes!

2021-06-02 16:04 UTC, cazala commented on webapp/src/modules/translation/locales/es.json
> +      "title": "Meta transacción",
joder!

2021-06-02 16:04 UTC, cazala approved these changes

2021-06-02 16:04 UTC, merged

2021-06-02 16:07 UTC, nicosantangelo commented on webapp/src/modules/translation/locales/es.json
> +      "title": "Meta transacción",
Meta transacción, saque vestimenta