feat: Add the wallet address in the account page
decentraland/marketplace pull request #351
Opened 2021-06-29 20:24 UTC by LautaroPetaccio

This PR does the following:
- It adds a the address and a copy button for its, below the username in the accounts page.
- It adds a popup so the address can be seen in full details.
- It abstracts the concept of timing stuff into a hook.

![copy-feature](https://user-images.githubusercontent.com/1120791/123862242-7ddf2180-d8fe-11eb-86e0-2ab61097e109.gif)

2021-06-30 12:46 UTC, nachomazzara commented on webapp/src/modules/translation/locales/zh.json
> +    "copied": "已复制 :heavy_check_mark:"
missing emoji?

2021-06-30 12:47 UTC, nachomazzara commented on webapp/src/lib/timer.spec.ts
> +import { renderHook, act } from '@testing-library/react-hooks'
❤️

2021-06-30 12:51 UTC, LautaroPetaccio commented on webapp/src/modules/translation/locales/zh.json
> +    "copied": "已复制 :heavy_check_mark:"
I've replicated the same line that's on the settings_page translations ([here](https://github.com/decentraland/marketplace/pull/351/files/5c2272e636bd59443e83e12dd64abc6ae0b7582e#diff-7ca97b120f16479fe42c01573b822edbb01297bfb74c09dd6a0c8fd46b91d2c9R267)).
But upon checking it, it seems to show the text `:heavy_check_mark:`. Should I change it in all the translations?

2021-06-30 16:24 UTC, cazala approved these changes
LGTM! There seems to be a conflict on the `package.json` tho, resolving that we're good to go

2021-06-30 18:54 UTC, nicosantangelo requested changes
Awesome work 🔥

2021-06-30 18:54 UTC, nicosantangelo commented on webapp/src/components/AccountPage/AccountPage.tsx
> +const copyAddressDesktop = (
In general, if a function is returning a JSX element, it should be a Component. This helps avoid a few problems like hooks not working and keeps the code a bit more consistent. Same goes for `copyAddressMobile` below!

Moreover, extracting this code is OK, but keeping with our own guidelines we tend to keep the JSX on the component that's using it **unless** it's needed in 2+ places (we could argue that some pieces of code are repeated but extracting them is overkill). IF we do extract it, we try to keep it in it's own folder+files.

Again, nothing wrong with the code per-se

2021-06-30 18:54 UTC, nicosantangelo commented on webapp/src/components/AccountPage/AccountPage.tsx
> +        <span className="copy">{t('settings_page.copy_address')}</span>
I think the I18n key here should be account_page right? we could also move it to a common key like global or the like

2021-06-30 18:56 UTC, nicosantangelo commented on webapp/src/components/AccountPage/AccountPage.tsx
> +  const [hasCopiedAddress, handleCopying] = useTimer(1200)
Sorry, one more thing, following the React hook naming conventions, the method should be called `setHasCopiedAddress` like it was called [here](https://github.com/decentraland/marketplace/pull/351/files#diff-27bae567c208e7553e5d83ce3d9376e8efb65574c4aef007dcc4e56a319c3bcfL31)

same goes for the line [here](https://github.com/decentraland/marketplace/pull/351/files#diff-27bae567c208e7553e5d83ce3d9376e8efb65574c4aef007dcc4e56a319c3bcfR32)

2021-06-30 19:34 UTC, cazala commented on webapp/src/components/AccountPage/AccountPage.tsx
> +  const [hasCopiedAddress, handleCopying] = useTimer(1200)
that would be right for a `useState` hook but this is a custom hook: https://github.com/decentraland/marketplace/pull/351/files#diff-ce54687ac19194251ade742703e87bf50231b4061c93dd39ffc1fa60adaf7b3cR18

the second deconstructed prop is the `startTimer`, not a setter.

2021-06-30 19:36 UTC, cazala commented on webapp/src/components/AccountPage/AccountPage.tsx
> +              {isMobile() &&
could we use a ternary here? we are calling `isMobile()` twice, also to keep the code more dry

2021-06-30 20:03 UTC, LautaroPetaccio commented on webapp/src/components/AccountPage/AccountPage.tsx
> +              {isMobile() &&
The thing is that the the button is placed in a different place if the page is viewed in mobile or desktop, so if we used only one ternary, we would have to repeat part of the code.

If you think that it's fine to repeat that section, I can change it in a heart beat.

2021-06-30 20:18 UTC, LautaroPetaccio commented on webapp/src/components/AccountPage/AccountPage.tsx
> +  const [hasCopiedAddress, handleCopying] = useTimer(1200)
That's correct, but we can think the `useTimer` as a normal hook, as it sets what it returns. It's true that it's not exporting the exact method that changes the value, but we can treat it as if it does.

Both names are correct though, whichever you think is right works for me.

2021-06-30 20:24 UTC, cazala commented on webapp/src/components/AccountPage/AccountPage.tsx
> +              {isMobile() &&
ahh you are right, mala mia, i didn't see the `<div/>` 😅

2021-06-30 20:27 UTC, cazala commented on webapp/src/lib/timer.ts
> +    setTimeoutId(newTimeoutId)
This is super minor, but you don't really need a re-render of the component when you modify the `timeoutId` (unlike the `isRunning` which does require a re-render when modified). So you could use a mutable reference here, which is what's usually used for timeoutIds: https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

2021-06-30 20:31 UTC, LautaroPetaccio commented on webapp/src/lib/timer.ts
> +    setTimeoutId(newTimeoutId)
Great catch! I'll check that out to see if I can implement it.

2021-07-01 14:57 UTC, nicosantangelo approved these changes

2021-07-01 14:58 UTC, merged