chore: extracts types and a component to their corresponding folders
decentraland/marketplace pull request #352
Opened 2021-06-29 20:38 UTC by nicosantangelo

In preparation for https://github.com/decentraland/marketplace/pull/349

2021-06-30 16:21 UTC, cazala requested changes

2021-06-30 19:21 UTC, nicosantangelo commented on webapp/src/modules/routing/actions.ts
> +export type BrowseActionNFTsAction = ReturnType<typeof browseNFTs>
Lol yes

2021-06-30 20:42 UTC, nicosantangelo commented
Fixed :)

2021-06-30 20:43 UTC, nicosantangelo commented
Updated 😄

2021-07-01 15:07 UTC, cazala approved these changes

2021-07-01 16:32 UTC, merged