[WIP] feat: Add parcel coordinates
decentraland/marketplace pull request #354
Opened 2021-06-30 19:29 UTC by LautaroPetaccio

This PR adds a section in the estate details that shows the coordinates of the parcels that form the estate being detailed.
Clicking a parcel will navigate you to the details of the parcel.

![coordinates](https://user-images.githubusercontent.com/1120791/124019313-47b5a680-d9bf-11eb-8789-792060b4fda0.gif)

2021-07-06 17:06 UTC, nicosantangelo requested changes
### UI/UX things:

1) I think we should hide the `show more` link when the amount of parcels is less than a certain threshold. It's a bit tricky considering mobile. It also looks weird when I click it:

https://user-images.githubusercontent.com/692077/124635890-52a88500-de5e-11eb-94a5-a45482f10407.mov

2) I think the link height for coordinates is bigger than what's containing when we have a few coordinates:

![image](https://user-images.githubusercontent.com/692077/124638314-30fccd00-de61-11eb-80d1-16ce8cdd43f6.png)

2021-07-06 19:59 UTC, LautaroPetaccio commented on webapp/src/components/NFTPage/EstateDetail/ParcelCoordinates/ParcelCoordinates.tsx
> +          <Link to={locations.parcel(parcel.x.toString(), parcel.y.toString())}>
The replace worked like a charm!

2021-07-07 16:13 UTC, nicosantangelo requested changes
This is awesomee 🔥.

https://user-images.githubusercontent.com/692077/124793200-235c4b80-df24-11eb-9ef9-88ad69f9962b.mov

Last two things:
- I think we still need to address [this](https://github.com/decentraland/marketplace/pull/354/files#r664705304) right? To remove (if I understood correctly) styles like [this one](https://github.com/decentraland/marketplace/blob/master/webapp/src/components/Atlas/Popup/Popup.css#L28)

- I think there's a slight problem with updating the need for a SEE MORE. I'm guessing that it's tied to the `resize` but it doesn't trigger when I navigate between estates, which leads to this:

https://user-images.githubusercontent.com/692077/124793200-235c4b80-df24-11eb-9ef9-88ad69f9962b.mov

https://user-images.githubusercontent.com/692077/124793115-0de72180-df24-11eb-9134-f22ea66d5062.mov

2021-07-08 14:16 UTC, nicosantangelo approved these changes

2021-07-08 14:16 UTC, merged