address validation for accounts
decentraland/marketplace pull request #460
Opened 2021-11-13 20:19 UTC by mercush

Here is my attempt to resolve [this issue](https://github.com/decentraland/marketplace/issues/447). Please forgive me if my code is bad. This is my first attempt at an open-source contribution. Would be very happy to take suggestions :).

2021-11-13 21:45 UTC, nachomazzara commented on webapp/src/components/AccountPage/AccountPage.tsx
> +    const response = baseAPI.request('get', '/assets/', params)
What do you think of just use just web3x or ethers to check if the address is valid or not? also, we should accept `ens` in order to resolve them in the near future https://app.zenhub.com/workspaces/dapps-5ffc44ecec9f8500140e173c/issues/decentraland/marketplace/448

2021-11-13 21:46 UTC, nachomazzara requested changes
Thanks for the collaboration! I left a comment

2021-11-14 05:38 UTC, mercush commented
I made another commit that supports ens resolution for /account and uses web3 to validate addresses. Let me know if you have any other suggestions!

2021-11-15 18:26 UTC, cazala commented
Hey @mercush this is awesome! There's one thing that would make it even better, we are trying to move away from web3x (since it's not maintained anymore) and use ethers instead. There are still some parts of the code that use it (like the Bids module) but everything else has been re-written to ethers and hopefully soon we'll be able to remove the dependency and use only ethers. Would you like to use the the ethers ENS helpers instead of the web3x ones? Here's some docs on how to use it, it's pretty much the same thing as web3x: https://docs.ethers.io/v5/api/providers/provider/#Provider--ens-methods

2021-12-04 18:18 UTC, mercush commented
Hey, I've been busy for the last couple of weeks so I haven't worked on this much. I'm trying to implement ethers right now but I don't see anywhere in the repo where it's been used before. Can you give me an example of a file where ethers has been used instead of web3x?

2021-12-10 20:59 UTC, cazala commented
hey @mercush, we usually use a helper `sendTransaction` on the dApps that abstract several things away (like getting the right provider, sending either a transaction or a meta-transaction according to the connected chain, etc), but you can look into that helper to find out how to get a provider and stuff like that: https://github.com/decentraland/decentraland-dapps/blob/master/src/modules/wallet/utils.ts#L86-L138

2021-12-10 23:25 UTC, mercush commented
Ok. I think that should do the trick. Let me know if there's anything else I should do to this pr.

2021-12-27 20:57 UTC, cazala requested changes

2021-12-27 20:57 UTC, cazala commented on webapp/src/modules/account/selectors.ts
> +  await provider.getResolver(address).then((res) => {
This seems to always return the address of the resolver, but not the address mapped by the ENS. No matter what ENS I use to test this it always redirects me to `0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41` which is the ENS resolver contract.

2021-12-27 20:57 UTC, cazala commented on webapp/src/modules/account/selectors.ts
> +    console.log('res', res)
oops this console log slipped thru

2021-12-27 20:57 UTC, cazala commented on webapp/src/modules/account/selectors.ts
> +      console.log('parsed address', parsedAddress)
same as above

2022-01-05 01:14 UTC, nachomazzara commented
@mercush are you willing to finish the PR?

2022-01-07 03:21 UTC, mercush commented
Yes. I've just been busy for the last couple of weeks.

2022-01-16 16:40 UTC, mercush commented
On second thought, I probably won't be able to work on this again for a while so I don't think I'll finish it.

2022-01-17 15:37 UTC, closed without merging