feat: Collection Detail Page
decentraland/marketplace pull request #468
Opened 2021-11-24 00:02 UTC by fzavalia

2021-11-24 18:37 UTC, fzavalia commented on webapp/src/components/AssetCard/AssetCard.tsx
> -import listedSvg from '../../images/listed.svg'
Removed the svg because I could use the icon from decentralan-ui instead

2021-11-24 18:39 UTC, fzavalia commented on webapp/src/components/CollectionList/CollectionList.tsx
> -  // Amount of collections without applying any filters.
The pros of doing this were less than not doing it so I'm removing it.
I was storing the first count which could be used as a total of all collections, however when fetching a collection for the collection detail page and going back to the list page, the total showed as 1.
Some other workaround could be developed but it was not worth the effort for the small problem it solved

2021-11-24 18:42 UTC, fzavalia commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +    onFetchCollection()
Not gonna change it now, but maybe this sort of side effects could be placed inside the location sagas and in this case, whenever the collection page is accessed, the collection could be fetched inside the saga

2021-11-24 18:43 UTC, fzavalia commented on webapp/src/components/CollectionPage/utils.ts
> +  `${process.env.REACT_APP_BUILDER_URL}?redirectTo=${encodeURIComponent(
We don't seem to have a place to store constants or config so I'm using the env here directly

2021-11-24 18:43 UTC, fzavalia commented on webapp/src/components/CollectionPage/utils.ts
> +      type: 'COLLECTION_DETAIL_BY_CONTRACT_ADDRESS',
This could be built by some common lib between the builder and the marketplace

2021-11-24 18:45 UTC, fzavalia commented on webapp/src/components/OnSaleList/OnSaleListElement/OnSaleListElement.module.css
> -.first-cell {
.module styles autocomplete seem to have a better time with camelCase than the kebab-case.
(styles.firstCell instead of styles['first-cell])

2021-11-24 20:42 UTC, cazala commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +    onFetchCollection()
the approach that we usually take for this type of behavior is creating an `AssetProvider` (ie `CollectionProvider`) that you can pass the id of the asset and it will load it, and pass it down to the children. We have this for items and nfts in the marketplace, for lands and other stuff in the builder. So then you don't really care about the routes where it's needed, you just wrap your render with this provider and you can use the asset as if it was already loaded. Same thing can be also created as a hook here since we are using React 17, like `const [collection, isLoading] = useCollection(address)`

2021-11-24 21:07 UTC, cazala requested changes

2021-11-24 21:07 UTC, cazala commented on webapp/.ci/.env.dev
> +REACT_APP_BUILDER_URL=https://builder.decentraland.io
⚠️ We should add this to the [vercel.json](https://github.com/decentraland/marketplace/blob/master/webapp/vercel.json) otherwise the pull request previews won't work

2021-11-24 21:11 UTC, cazala commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +                      <Table.Row key={item.id} className={styles.row}>
Should we wrap this with a `<Link to={locations.itemDetail(item.id)}>` ?

2021-11-24 21:21 UTC, fzavalia commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +                      <Table.Row key={item.id} className={styles.row}>
Absolutely 🙂

2021-11-25 02:45 UTC, fzavalia commented on webapp/.ci/.env.dev
> +REACT_APP_BUILDER_URL=https://builder.decentraland.io
Added

2021-11-25 16:06 UTC, fzavalia commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +    onFetchCollection()
I went for  the CollectionProvider pattern because we currently have no hooks for this and didn't want to change what we already use.
The good thing about the provider is that it does not request everytime the user enters the page as the required data is already in the store.
Thanks for the idea @cazala 😁

2021-11-25 16:11 UTC, fzavalia commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +                      <Table.Row key={item.id} className={styles.row}>
Done, I wrapped only the image and name cell instead of the whole row. This is because it might bring conflicts with the dropdown, even when preventing bubbling (or propagation, I don't remember the name of what prevents events to travel upwards) as the user might click the row instead and be confused as to how they traveled to the item instead of the builder.

2021-11-25 16:14 UTC, fzavalia commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +                      <Table.Row key={item.id} className={styles.row}>
And TBH adding the link to the whole row was messing up the styles 😅

2021-11-26 13:58 UTC, cazala approved these changes

2021-11-29 16:10 UTC, merged