feat: Sales page in My Store
decentraland/marketplace pull request #498
Opened 2021-12-24 16:30 UTC by fzavalia

2021-12-27 20:01 UTC, cazala requested changes

2021-12-27 20:01 UTC, cazala commented on webapp/src/components/OnSaleList/AssetCell/AssetCell.tsx
> +  const link = asset.itemId
Oops, polygon assets always have `itemId` (both items and nfts) so this will always produce links to items. It should be `asset.tokenId ? ...` instead.

2021-12-27 20:11 UTC, cazala commented
I noticed that the mobile view of the sales page has a strange layout: 

<img width="458" alt="Screen Shot 2021-12-27 at 16 53 45" src="https://user-images.githubusercontent.com/2781777/147503602-baf0cec8-80a0-4211-9d20-2259a4d9faa7.png">

We could do something more like the transaction history:

<img width="995" alt="Screen Shot 2021-12-27 at 16 52 40" src="https://user-images.githubusercontent.com/278177

<img width="486" alt="Screen Shot 2021-12-27 at 16 52 47" src="https://user-images.githubusercontent.com/2781777/147504118-1bee6014-91dd-452f-90b9-b7735aff0596.png">
7/147504117-e066ee11-ed05-4492-a62a-51325b0afc94.png">

I notice that is also the case with the On Sale page so i think we can just add a ticket to go over the newly added pages and make them more responsive if needed, no need to do it on this PR 👍

2021-12-27 21:54 UTC, fzavalia commented on webapp/src/components/OnSaleList/AssetCell/AssetCell.tsx
> +  const link = asset.itemId
Sure! thanks for the catch

2021-12-28 14:29 UTC, cazala approved these changes

2021-12-28 14:54 UTC, merged