Deselect 'my store' tab when seeing a collection
decentraland/marketplace pull request #518
Opened 2022-01-12 03:55 UTC by nishit-g

Problem : 
By using this link https://market.decentraland.org/collections/0xb96697fa4a3361ba35b774a42c58daccaad1b8e1 we should deselect the My store tab by either do not select any tab or by selecting the collectibles one.

Solution : Selects the collectibles one.

closes #517

2022-01-13 12:41 UTC, cazala commented on webapp/src/components/CollectionPage/CollectionPage.tsx
> +      <Navigation activeTab={NavigationTab.COLLECTIBLES} />
Hi @nishit-g! The collection detail can be accessed from different parts of the app (like from an item detail, or from the collections section of My Store). This change in the PR makes it consistent when you navigate from an item detail to a collection detail (in both cases the Collectibles tab is active), but now it is inconsistent when you navigate from your collections' list in My Store (it switches back and forth between My Store and Collectibles).

I think the best solution is to turn this tab off in the collection detail rather than keeping Collectibles or My Store active.

```suggestion
      <Navigation />
```

2022-01-13 13:06 UTC, cazala approved these changes

2022-01-19 13:36 UTC, cazala requested changes
@nishit-g there seems to be an error that's making the build fail: 

```
'NavigationTab' is declared but its value is never read. 
```

2022-01-19 15:21 UTC, nishit-g commented
@cazala sorry my bad, fixed it!

2022-01-20 16:06 UTC, merged