feat: Add ENS support to /accounts page
decentraland/marketplace pull request #526
Opened 2022-01-18 20:07 UTC by juanmahidalgo

Adds the logic to get the address if a ENS one is provided in the URL.

https://user-images.githubusercontent.com/8763687/150010624-3cf7bc86-48af-4dcb-9ba4-c91ccde3820b.mov

2022-01-18 21:05 UTC, nicosantangelo commented
Works great!

Question @juanmahidalgo @cazala. Are we opting to use the component and a hook for this over a saga for a particular reason? on first inspection it looks like it could be a saga that can be triggered with an from this or another component.

It is true that a hook works in a similar way, but trying to adhere to the rest of the arch of the project. However if this is something super niche it might be cool to keep it there

2022-01-18 21:23 UTC, cazala commented
tbh i told juanma to use an effect because a saga seemed a bit overkill, since this just builds on top of a the invalid address redirect

2022-01-18 21:24 UTC, fzavalia commented
Would be nice to abstract the address logic into some sort of AddressProvider that takes care of all related to the address (getting it from the url or the wallet, redirecting if not valid or not found, resolving if it an ens) and returning the final address that should be used by the component.

For example:

```
<AddressProvider>{(address, isLoading) => ... }</AddressProvider>
```

2022-01-18 21:33 UTC, cazala commented
I like the `AddressProvider` approach 👍

2022-01-19 13:05 UTC, juanmahidalgo commented
Thanks for the feedback guys, turning the PR into draft while I work on the new `AddressProvider`

2022-01-19 19:18 UTC, fzavalia requested changes

2022-01-19 19:18 UTC, fzavalia commented on webapp/src/components/AccountPage/AccountPage.tsx
> +            {isLoading || isConnecting ? (
I would put all in the same ternary condition like 

```
          <>
            {isLoading || isConnecting ? (
              <Page>
                <Loader size="massive" active />
              </Page>
            ) : error ? (
              <Page>
                <Center>
                  <p className="secondary-text">{t(`address.${error}`)}</p>
                </Center>
              </Page>
            ) : address ? (
              <>
                {!isCurrentAccount ? <AccountBanner address={address} /> : null}
                <AssetBrowse
                  vendor={vendor}
                  address={address}
                  view={isCurrentAccount ? View.CURRENT_ACCOUNT : View.ACCOUNT}
                  isFullscreen={Boolean(isFullscreen)}
                />
              </>
            ) : null}
          </>
```

To avoid having the big loader moving the banner to the bottom.

![image](https://user-images.githubusercontent.com/24811313/150198226-232df9c0-05ec-451c-8343-98ab220a38e8.png)

2022-01-19 19:18 UTC, fzavalia commented on webapp/src/components/AddressProvider/AddressProvider.tsx
> +      setError(AddressError.INVALID)
This is not redirecting anymore, I would change the render of the AccountPage that when there is an address error, just render te redirect component

```
<Redirect to={locations.root()} />
```

If the intention is to show the error instead of redirecting, remove the Redirect comment

2022-01-19 19:33 UTC, juanmahidalgo commented on webapp/src/components/AddressProvider/AddressProvider.tsx
> +      setError(AddressError.INVALID)
@cazala suggested to show errors instead of redirecting, that could be confusing to the users due to the lack of feedback. I replaced the redirect logic in favor of the error messages so I'm removing the outdated comment :)

2022-01-19 19:35 UTC, juanmahidalgo commented on webapp/src/components/AccountPage/AccountPage.tsx
> +            {isLoading || isConnecting ? (
Good call Nan2, I wrote the big ternary first but ended up replacing with 3 of them trying to be clearer but I rather have the big one and avoid the big spinner pushing stuff down. Updated!

2022-01-19 19:45 UTC, fzavalia approved these changes
LGTM

2022-01-20 15:03 UTC, cazala approved these changes

2022-01-20 15:52 UTC, merged