Feat/change button for link in pagination
decentraland/marketplace pull request #619
Opened 2022-04-27 13:50 UTC by braianj

In order to perform this task, we took out three saga (buildBrowseURL, getCurrentBrowseOptions, getAddress) and put them in utils (buildBrowseURL) and the rest in selectors. 
As part of the process we created selectors that group other selectors, mainly the ones that get parameters from the url (getPaginationUrlParams, getAssetsUrlParams, getLandsUrlParams, getWearablesUrlParams), so we can use them in the getCurrentBrowseOptions selector.
Once this process was finished, the sagas that use these new selectors were updated.
Then we added in the AssetList.container.ts file the urlNext property to send the url to use in the href of the anchor tag.

2022-04-28 15:34 UTC, 2fd requested changes

2022-04-28 15:34 UTC, 2fd commented on webapp/src/components/AssetList/AssetList.container.ts
> +  urlNext: buildBrowseURL(state.router.location.pathname, { ...getCurrentBrowseOptions(state), page: (getPage(state) + 1)})
There are too many thing in only one line, try to move some functions call into variables to make it a little more readable, and don't repeat the call to `getPage`.

And access the `state` variable directly can be consider a bad practice, it could change at any given time and the only place expected to change how is access is in selectors, use the `getLocation` (from `connected-react-router` dependency) to access the location

2022-04-28 20:41 UTC, 2fd approved these changes

2022-05-03 20:52 UTC, cazala approved these changes

2022-05-03 20:52 UTC, cazala commented
Awesome 👏 👏 👏

2022-05-03 21:02 UTC, merged