feat: price too log for items
decentraland/marketplace pull request #641
Opened 2022-05-10 19:21 UTC by nicosantangelo

https://user-images.githubusercontent.com/692077/167705844-336e957d-803d-4c6a-b95f-c12c57722181.mov

2022-05-11 20:39 UTC, LautaroPetaccio requested changes

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/modules/translation/locales/en.json
> +    "learn_more": "Learn More",
This change seems to not have been replicated in the other languages.

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/components/BuyPage/utils.ts
> +      return toBN(price).gte(toBN(minSaleValue))
Isn't it lower than?
```suggestion
      return toBN(price).lt(toBN(minSaleValue))
```

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/components/BuyPage/utils.spec.ts
> +  describe('when there a min sale value', () => {
```suggestion
  describe('when there is a min sale value', () => {
```

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/components/BuyPage/utils.spec.ts
> +    })
Are we just covering minting of new items with this change?

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/components/BuyPage/utils.spec.ts
> +          isPriceTooLow(AssetType.ITEM, {
The name might be a bit weird, if the price is too low, why is it returning true for a min price that is lower than the price? It seems that the price is higher than the minimum amount.

2022-05-11 20:39 UTC, LautaroPetaccio commented on webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
> +    !isPriceTooLow(AssetType.ITEM, item) && isInDifferentChainId
Isn't the condition `isPriceTooLow(AssetType.ITEM, item) && !isInDifferentChainId`?

2022-05-11 20:48 UTC, nicosantangelo commented on webapp/src/modules/translation/locales/en.json
> +    "learn_more": "Learn More",
Good eye!

2022-05-11 20:50 UTC, nicosantangelo commented on webapp/src/components/BuyPage/utils.ts
> +      return toBN(price).gte(toBN(minSaleValue))
Correct, the function is actually fine, the refactored name was the problem. Changing tho!

2022-05-11 20:51 UTC, nicosantangelo commented on webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
> +    !isPriceTooLow(AssetType.ITEM, item) && isInDifferentChainId
fixed, related to the rename discussed above

2022-05-11 20:52 UTC, nicosantangelo commented on webapp/src/components/BuyPage/utils.spec.ts
> +          isPriceTooLow(AssetType.ITEM, {
fixed, related to the rename discussed above

2022-05-12 15:06 UTC, LautaroPetaccio requested changes

2022-05-12 15:24 UTC, LautaroPetaccio approved these changes

2022-05-12 18:58 UTC, merged