feat: use links instead of divs for badges
decentraland/marketplace pull request #645
Opened 2022-05-12 17:58 UTC by braianj

The CategoryBadge, GenderBadge and SmartBadge components were changed to create the url and send it to the IconBadge component.
IconBadge was also modified to accept the url.

2022-05-13 21:37 UTC, nicosantangelo requested changes
Careful, I've noticed that some files like `CategoryBadge.tsx`, `SmartBadge.tsx` and `IconBadge.tsx` are not properly linted with prettier!

This looks super!

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +  React.useEffect(() => {
We could just import `useEffect` right?

```suggestion
  useEffect(() => {
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +import { locations } from '../../../modules/routing/locations'
We have some (annoying maybe :P) [import order standards](https://www.notion.so/decentraland/dApps-Standards-760ee6551c9f4c00aa71f7d9c50a7646#8d48e37938124a41ac664112cb1e27f6) we should follow!

```suggestion
import { t } from 'decentraland-dapps/dist/modules/translation/utils'
import { getSearchWearableSection } from '../../../modules/routing/search'
import { locations } from '../../../modules/routing/locations'
import IconBadge from '../IconBadge'
import { Props } from './CategoryBadge.types'
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +  const href = React.useMemo(() => {
We could just import `useMemo` right?

```suggestion
  useMemo(() => {
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +    !section && delete browseProps.section
We could maybe type `browseProps` so we don't have to delete a prop (and maybe add more later

```ts
    const browseProps: BrowseOptions = { assetType: assetType }
    if(section) {
      browseProps.section = section
    }
```

and, this is just a suggestion, maybe we can call it browseOptions to follow the type

what do you think?

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/IconBadge/IconBadge.tsx
> +  const childrenInt = React.useMemo(() => (
We could just import `useMemo` right?

```suggestion
  useMemo(() => {
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/IconBadge/IconBadge.tsx
> +import { Link } from 'react-router-dom'
We have some [import order standards](https://www.notion.so/decentraland/dApps-Standards-760ee6551c9f4c00aa71f7d9c50a7646#8d48e37938124a41ac664112cb1e27f6) we should follow! (Sorry 👮‍♂️ )

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/IconBadge/IconBadge.tsx
> +  }
What do you think of the, maybe more succint:

```ts
  return href ? (
    <Link
      className={classNames('IconBadge', className)}
      onClick={onClick}
      to={href}
    >
      {childrenInt}
    </Link>
  ) : (
    <div className={classNames('IconBadge', className)} onClick={onClick}>
      {childrenInt}
    </div>
  )
```

my reasoning is that ternary operators is what we normally use inside JSX so it looks a bit more natural

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/SmartBadge/SmartBadge.container.ts
> +export default connect()(SmartBadge)
Same thing as the [CategoryBadge.container.ts](https://github.com/decentraland/marketplace/pull/645/files#diff-9d2230b63c0fd2e01523e58a22e7ce5e5b4fd84dcc49433970d851924bed6934) with the index and this file!

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/SmartBadge/SmartBadge.tsx
> +import { locations } from '../../../modules/routing/locations'
We have some (annoying maybe :P) [import order standards](https://www.notion.so/decentraland/dApps-Standards-760ee6551c9f4c00aa71f7d9c50a7646#8d48e37938124a41ac664112cb1e27f6) we should follow! (super sorry lol)

```suggestion
import { Section } from '../../../modules/vendor/decentraland'
import { locations } from '../../../modules/routing/locations'
import IconBadge from '../IconBadge'
import { Props } from './SmartBadge.types'
import './SmartBadge.css'
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/AssetPage/SmartBadge/SmartBadge.tsx
> +  const href = React.useMemo(() => locations.browse({
We could just import `useMemo` right?

```suggestion
  useMemo(() => {
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/GenderBadge/GenderBadge.container.ts
> +export default connect()(GenderBadge)
Same thing as the [CategoryBadge.container.ts](https://github.com/decentraland/marketplace/pull/645/files#diff-9d2230b63c0fd2e01523e58a22e7ce5e5b4fd84dcc49433970d851924bed6934) with the index and this file!

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/GenderBadge/GenderBadge.tsx
> +  const href = React.useMemo(() => locations.browse({
We could just import `useMemo` right?

```suggestion
  useMemo(() => {
```

2022-05-13 21:37 UTC, nicosantangelo commented on webapp/src/components/GenderBadge/GenderBadge.tsx
> +import { locations } from '../../modules/routing/locations'
We have some [import order standards](https://www.notion.so/decentraland/dApps-Standards-760ee6551c9f4c00aa71f7d9c50a7646#8d48e37938124a41ac664112cb1e27f6) we should follow! (😅 )

2022-05-13 22:04 UTC, braianj commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +import { locations } from '../../../modules/routing/locations'
Many thanks for remember me this

2022-05-13 22:18 UTC, braianj commented on webapp/src/components/AssetPage/IconBadge/IconBadge.tsx
> +import { Link } from 'react-router-dom'
🙈

2022-05-13 22:22 UTC, braianj commented on webapp/src/components/AssetPage/IconBadge/IconBadge.tsx
> +  }
I think the same

2022-05-17 15:32 UTC, nicosantangelo commented on webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx
> +import { BrowseOptions } from '../../../modules/routing/types'
We should move this two lines up! as per standards 🙃

2022-05-17 20:05 UTC, merged