feat: create rental
decentraland/marketplace pull request #769
Opened 2022-08-11 01:55 UTC by cazala

2022-08-18 20:02 UTC, cazala commented on webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx
> +              Create Rental
I added this button here to be able to test this modal from the Parcel detail page.

2022-08-18 20:06 UTC, cazala commented on webapp/src/index.css
> +  > iframe[style='position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;'] {
for some reason, every time I save a file and the marketplace is rebuilt, I get a `process is not defined` error in the console and then an invisible iframe blocks the whole screen.. i could figure out a way to fix the error, but this rule at least gets rid of that invisible iframe so I can keep working without having to reload the page

2022-08-19 19:35 UTC, LautaroPetaccio requested changes

2022-08-19 19:35 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +  const isInvalidDate = new Date(expiresAt).getTime() < Date.now()
What do you think about adding `expiration` to this variable name?
```suggestion
  const isInvalidExpirationDate = new Date(expiresAt).getTime() < Date.now()
```

2022-08-19 19:35 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              }}
What if we define a handler for these functions so we don't have to re-render the field when a re-render is triggered?

2022-08-19 19:35 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +  const createOptionHanlder = (periodOption: PeriodOption) => () => {
Would you mind changing this function to:
```suggestion
  const handlePeriodsOptionChange = (periodOption: PeriodOption) => () => {
```
so it follows the dApps standards.

2022-08-19 19:35 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              error={pricePerDayInput !== '' && isInvalidPrice}
There's a message in case an invalid date is set, but, there's no message for an invalid price, what do you think about setting one?

2022-08-19 19:35 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              </div>
Should we add a kind of error message saying that the user needs to set at least one period?

2022-08-19 19:43 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +  const createOptionHanlder = (periodOption: PeriodOption) => () => {
the thing is that the function itself is not a handler, is currying a handler with the period option, and return the handler itself.

2022-08-19 19:45 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              </div>
but should that error be shown all the time until the user selects a period? currently the 'put for rent' button is disabled if there's no period selected, so the user can't click it

2022-08-19 19:47 UTC, juanmahidalgo commented on webapp/src/index.css
> +  > iframe[style='position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;'] {
@cazala try running `npm install react-error-overlay@6.0.9 --save-dev`. If it gets fixed, feel free to push the `-lock` here :)

2022-08-22 14:05 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              </div>
I think it might be a bit annoying, you're right. I was trying to find a solution to the problem of "disabled buttons that don't show why", but this might be overkill.

2022-08-23 21:15 UTC, cazala commented on webapp/src/index.css
> +  > iframe[style='position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;'] {
it worked! thanks :)

2022-08-23 21:16 UTC, cazala commented on webapp/src/modules/rental/types.ts
> +  ONE_YEAR = 'one_year'
As discussed offline, didn't take this approach because using numbers as values for enums causes them to have 2 entries per value in the final record (typescript implementation), which makes it more difficult to get a list of all the values

2022-08-23 23:29 UTC, cazala commented on webapp/src/modules/rental/sagas.ts
> +    )
done 👍

2022-08-23 23:29 UTC, cazala commented on webapp/src/modules/rental/reducer.ts
> +    case CREATE_RENTAL_REQUEST: {
done 👍

2022-08-23 23:29 UTC, cazala commented on webapp/src/modules/rental/utils.ts
> +export async function getContractNonce(chainId: ChainId) {
done 👍

2022-08-24 00:08 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              error={pricePerDayInput !== '' && isInvalidPrice}
done 👍

2022-08-24 00:09 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +  const isInvalidDate = new Date(expiresAt).getTime() < Date.now()
done 👍

2022-08-24 00:09 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +              }}
done 👍

2022-08-24 00:11 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +  const createOptionHanlder = (periodOption: PeriodOption) => () => {
mm it has a `value` but how would you use the same handler to set the values of different Radio components?

2022-08-24 00:25 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +import './CreateRentalModal.css'
AFAIK it's not possible to theme components (like the Radios) using css modules, since it will screw up all the class names of the decentraland-ui components i'm trying to theme.

2022-08-24 00:27 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +import './CreateRentalModal.css'
for example: https://github.com/decentraland/marketplace/pull/769/files#diff-33b52f92e09f2ffd9b051dde3817f0f24e6965eb91c1b7794f13014e487cb9e7R38-R52

2022-08-24 15:57 UTC, cazala commented on webapp/src/components/CreateRentalModal/CreateRentalModal.tsx
> +import './CreateRentalModal.css'
nvm, i forgot about `:global` for these cases, done 👍

2022-08-24 17:47 UTC, LautaroPetaccio approved these changes

2022-08-24 17:47 UTC, LautaroPetaccio commented on webapp/src/modules/rental/contract.spec.ts
> +    })
There's a problem with this test, it checks for a truthy value, but the method could anything and it will still pass. You would have to mock ethers or directly remove the test if it's too much of a problem as this test could be a bit tricky to understand.

2022-08-24 17:47 UTC, LautaroPetaccio commented on webapp/src/modules/rental/reducer.spec.ts
> +describe('when reducing a CREATE_RENTAL_SUCCESS action', () => {
```suggestion
describe('when reducing a CREATE_RENTAL_FAILURE action', () => {
```

2022-08-24 17:47 UTC, LautaroPetaccio commented on webapp/src/modules/rental/reducer.spec.ts
> +    }
You can abstract all state definitions by adding a `beforeEach` on top of the describe scope with the following:
```
let state
beforeEach(() => {
  state = {
        loading: [
        createRentalRequest(nft, 100, [PeriodOption.ONE_WEEK], 1976562675847)
      ],
      data: {},
      error: 'some error'
  }
})
```
This state should be functional to all `its` down below.

2022-08-24 17:47 UTC, LautaroPetaccio commented on webapp/src/modules/rental/utils.spec.ts
> +    rentalsMock.assetNonce.mockResolvedValueOnce(BigNumber.from(2))
Would you mind moving these mocks to the `beforeEach`? The idea behind this is to build the context on it so the it is used to define expectations.

2022-08-24 20:48 UTC, cazala commented on webapp/src/modules/rental/reducer.spec.ts
> +describe('when reducing a CREATE_RENTAL_SUCCESS action', () => {
thanks <3

2022-08-24 20:56 UTC, cazala commented on webapp/src/modules/rental/contract.spec.ts
> +    })
I changed it to expect the resolved value to be an instance of `ethers.Contract`

2022-08-24 20:57 UTC, cazala commented on webapp/src/modules/rental/reducer.spec.ts
> +    }
done 👍

2022-08-24 21:36 UTC, cazala commented on webapp/src/modules/rental/utils.spec.ts
> +    rentalsMock.assetNonce.mockResolvedValueOnce(BigNumber.from(2))
done 👍

2022-08-24 21:38 UTC, merged