feat: create rental listing adjustments
decentraland/marketplace pull request #786
Opened 2022-08-31 20:29 UTC by cazala

This PR splits the `CreateRentalModal` into a `RentalModal` with several views. This paves the road to add later more views like the ones for editing a listing, cancel it, or rent it again. The authorization step and the listing creation step where separated into their own views and the styles were adjusted to match the latest figma. Finally the new confirmation step was added as a new view as well.

Authorization Step:
<img width="940" alt="Screen Shot 2022-08-31 at 17 22 38" src="https://user-images.githubusercontent.com/2781777/187775512-4019d89f-b6f9-4ad2-a43e-4e1b385c4aa5.png">

Authorization Step (Signing the tx):
<img width="681" alt="Screen Shot 2022-08-31 at 17 23 50" src="https://user-images.githubusercontent.com/2781777/187775577-92eac724-429a-4972-9a2d-ded92e17a725.png">

Authorization Step (Waiting for tx to be mined):
<img width="715" alt="Screen Shot 2022-08-31 at 17 23 58" src="https://user-images.githubusercontent.com/2781777/187775623-29f93b68-2bff-4472-8ce6-b58288610401.png">

Create Listing Step (Pristine):
<img width="729" alt="Screen Shot 2022-08-31 at 17 24 35" src="https://user-images.githubusercontent.com/2781777/187775679-448f974f-51f8-48fe-b61d-e2724724ff10.png">

Create Listing Step (Completed):
<img width="831" alt="Screen Shot 2022-08-31 at 17 25 40" src="https://user-images.githubusercontent.com/2781777/187775746-5e2fce1b-366e-47de-94a6-295daca67722.png">

Confirmation Step:
<img width="772" alt="Screen Shot 2022-08-31 at 17 25 48" src="https://user-images.githubusercontent.com/2781777/187775802-a9167197-1cdc-4a1a-bccb-066de8838f52.png">

2022-09-01 17:26 UTC, LautaroPetaccio requested changes

2022-09-01 17:26 UTC, LautaroPetaccio commented on webapp/src/components/CreateRentalModal/RentalModal.container.ts
> +})
What I'm not seeing here is the cancel function. Should launch an action to clear the errors as well as executing the handler that comes from the creator of this component?

2022-09-01 17:26 UTC, LautaroPetaccio commented on webapp/src/modules/translation/locales/es.json
> +      "notice_line_two": "Cuando el período de alquiler termine tiene dos opciones :",
Does it requires a whitespace or is it a typo?
```suggestion
      "notice_line_two": "Cuando el período de alquiler termine tiene dos opciones:",
```

2022-09-01 17:51 UTC, cazala commented on webapp/src/components/CreateRentalModal/RentalModal.container.ts
> +})
i left the `open` and `onCancel` as props for now because I didn't know how we wanted to use this component (since the Manage screen is not ready yet). Once we integrate this into the final screen we could create an action if we want to open this from redux and impact some parts of the state (like clearing the error).

2022-09-01 17:53 UTC, cazala commented on webapp/src/components/ManaToFiat/ManaToFiat.tsx
> +        .marketMANAToUSD(value)
Usually it should be loaded by the time this is executed, since the price is fetched as soon as the app loads and then is cached for the rest of the life of the app.

2022-09-01 17:53 UTC, cazala commented on webapp/src/components/ManaToFiat/ManaToFiat.tsx
> +        .marketMANAToUSD(value)
So there's no idle time for it to load

2022-09-02 12:22 UTC, LautaroPetaccio approved these changes

2022-09-02 12:27 UTC, merged