feat: Add emote categories to originals sidebar
decentraland/marketplace pull request #812
Opened 2022-09-14 13:49 UTC by cyaiox

This PR adds the emote section and categories to the `Originals` sidebar.

![image](https://user-images.githubusercontent.com/3170051/190172124-f0ad26f2-803a-438f-bd7c-14620aaa5d29.png)

Closes #808

2022-09-15 14:50 UTC, fzavalia commented on webapp/src/modules/routing/sagas.ts
> +        const emoteCategory =
Can this be tested if it not too complicated?

2022-09-15 14:51 UTC, fzavalia requested changes
🙏

2022-09-15 14:56 UTC, cyaiox commented on webapp/src/modules/routing/sagas.ts
> +        const emoteCategory =
sure!

2022-09-16 01:50 UTC, fzavalia approved these changes

2022-09-16 13:00 UTC, merged