feat: Introduce MVMF badge & MVMF Page
decentraland/marketplace pull request #856
Opened 2022-10-05 18:10 UTC by juanmahidalgo

![image](https://user-images.githubusercontent.com/8763687/194131175-f228ae31-e05d-440c-ae76-d75c80faab8e.png)

![image](https://user-images.githubusercontent.com/8763687/194131505-c3ed43a1-b867-47d1-b2c3-781079208431.png)

![image](https://user-images.githubusercontent.com/8763687/194131535-d669d812-d008-456e-bdbf-23a52598b0f7.png)

Closes #853 
Closes #855

2022-10-05 18:34 UTC, cazala requested changes

2022-10-05 18:34 UTC, cazala commented on webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.tsx
> +const MVMFTag = 'MVMF 2022'
According to notion the tag is `MVMF22`

2022-10-05 18:34 UTC, cazala commented on webapp/src/modules/routing/types.ts
> +  contractAddresses?: string[]
I believe we already have a `contracts` parameter that serves the same purpose as this. This is because the NFTs already supported filtering by multiple contract addresses. We should use that one instead of duplicating it.

2022-10-05 18:34 UTC, cazala commented on webapp/src/modules/vendor/decentraland/item/types.ts
> +  contractAddresses?: string[]
There's a single `contractAddress` filter for items, we should refactor it to be an array instead of supporting both single and multiple params. Also it is called `contracts` in the nft filters, I think we should name it the same way for consistency: https://github.com/decentraland/marketplace/blob/master/webapp/src/modules/vendor/decentraland/nft/types.ts#L26

2022-10-05 18:34 UTC, cazala commented on webapp/src/modules/routing/sagas.ts
> +    contractAddresses
here we have both `contracts` and `contractAddresses` that serve the same purpose

2022-10-06 08:25 UTC, juanmahidalgo commented on webapp/src/modules/routing/types.ts
> +  contractAddresses?: string[]
Absolutely right, I completely missed the `contracts` param. Updated to reuse it!

2022-10-06 08:25 UTC, juanmahidalgo commented on webapp/src/modules/vendor/decentraland/item/types.ts
> +  contractAddresses?: string[]
Agreed! Updated :)

2022-10-07 16:28 UTC, cazala requested changes
When I click on the `Metaverse Festival` tab, it takes me to the `Listings` section first, instead of the `Store`:

<img width="1130" alt="Screen Shot 2022-10-07 at 13 26 50" src="https://user-images.githubusercontent.com/2781777/194602307-e91ad032-5116-4e8e-ad84-d0085486abda.png">

2022-10-07 16:28 UTC, cazala commented on webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.tsx
> +      const addresses = await builderAPI.fetchAddressesByTag([MVMFTag])
should we wrap this in a try/catch?

2022-10-07 16:28 UTC, cazala commented on webapp/src/components/MVMFPage/MVMFPage.types.ts
> +  fetchEventContracts: typeof fetchEventRequest
Could we rename this to `onFetchEventContracts` to keep it consistent with standards?

2022-10-07 16:37 UTC, juanmahidalgo commented on webapp/src/components/MVMFPage/MVMFPage.types.ts
> +  fetchEventContracts: typeof fetchEventRequest
done!

2022-10-07 16:37 UTC, juanmahidalgo commented on webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.tsx
> +      const addresses = await builderAPI.fetchAddressesByTag([MVMFTag])
sure! updated

2022-10-07 16:48 UTC, cazala approved these changes

2022-10-07 17:14 UTC, merged