feat: Add "On Rent" section listing rentals
decentraland/marketplace pull request #910
Opened 2022-10-26 15:20 UTC by juanmahidalgo

Closes #749

![image](https://user-images.githubusercontent.com/8763687/198067004-559d13f3-3918-431e-9711-81771f4815b1.png)

2022-11-01 13:30 UTC, cazala commented
Is it okay that clicking on a parcel takes you to the detail page, instead of the manage page?

2022-11-01 14:28 UTC, LautaroPetaccio requested changes

2022-11-02 13:49 UTC, cazala reviewed
Is it okay that clicking on a parcel takes you to the detail page, instead of the manage page?

2022-11-02 14:29 UTC, LautaroPetaccio commented
It's not @cazala , great catch!

2022-11-03 11:32 UTC, juanmahidalgo commented on webapp/src/modules/ui/browse/selectors.ts
> +  Object.values(nftsById)
sure! tests added for the whole file :)

2022-11-03 11:32 UTC, juanmahidalgo commented on webapp/src/components/OnSaleOrRentList/OnSaleOrRentList.tsx
> +  console.log('elements: ', elements)
done!

2022-11-03 11:41 UTC, juanmahidalgo commented
> Is it okay that clicking on a parcel takes you to the detail page, instead of the manage page?

Updated!

2022-11-03 15:54 UTC, LautaroPetaccio approved these changes

2022-11-04 11:44 UTC, merged